### ISSUE TITLE
doubt regarding /dc_motor/command

### ISSUE THREAD

**Issue by raghavthakar** [nilseuropa/gazebo_ros_motors#1]
Hi! Thanks for making such a useful plugin! One question: what exactly does /dc_motor/command topic take? I believe it is not the desired angular velocity as mentioned in documentation as any command over 1.0 gives angular velocity as 14.97 in /dc_motor/velocity topic. Motor velocity seems to be directly proportional to the input at /dc_motor/command. Could you please clarify? Again, thank you very much for making this.

**Comment by nilseuropa** [comment]
Hi,

there are two plugins in this repository.

The DC motor plugin as stated in the documentation takes a **normalized** [-1.0,+1.0] input command of the applied voltage that scales to _motor_nominal_voltage_ parameter.

On the other hand the ODE Joint Motor Plugin does exactly what you are looking for. Although that's just a simple "ideal" motor, it takes in desired angular velocity.
