### ISSUE TITLE
Simulating failures

### ISSUE THREAD

**Issue by phuicy** [nilseuropa/gazebo_ros_motors#2]
Hi 

Thanks for your excellent plugin. 
I would like to extend it to allow the simulations of motor failures, but the equation seem a bit intertwined at the moment (https://github.com/nilseuropa/gazebo_ros_motors/blob/master/src/gazebo_ros_dc_motor.cpp#L209).
Do you have any documentation on the derivation of the equations?
Also I am curious about friction is used?

thanks,
Guy

**Comment by nilseuropa** [comment]
Hi,

thanks, simulating failures sounds like a great improvement. :) 

I've added the output of DSolve as PDF to the `doc` folder, but that's a mess as well.

Friction is defined on the actuated joint in the URDF,
```<dynamics damping="${motor_param['joint_damping']}" friction="${motor_param['joint_friction']}"/>```
it is committed to the physics engine to calculate it into the actual load torque.

cheers,
m.

**Comment by phuicy** [comment]
This is excellent thank you. 

Having the initial equations and knowing it was through Dsolve, will mean we can extend it.

**Comment by nilseuropa** [comment]
Cool!
