### ISSUE TITLE
How to publish joint_states for two motors?

### ISSUE THREAD

**Issue by snrdevs** [nilseuropa/gazebo_ros_motors#3]
Hi all, 
I'm building a mobile robot, and I want to use, "joint_motor" in my project. I prepared a URDF for my robot and launched it in Gazebo. I set up my left_wheel & right_wheel joints as mentioned in your Readme file, and it works properly. 

My question is, I want to publish joint_states messages for my both wheels. When I look into code, I think it's only for one wheel (or motor). So, it publishes the state of last wheel in the URDF (in this case right_wheel). How can I publish joint_states messages for my both wheels? 

Thanks in advance. 

`   // joint state publisher
    gazebo_ros_->getParameterBoolean  ( publish_motor_joint_state_, "publish_motor_joint_state", false );
    if (this->publish_motor_joint_state_) {
        joint_state_publisher_ = gazebo_ros_->node()->advertise<sensor_msgs::JointState>("main_wheel_states", 1000);
        ROS_INFO_NAMED("motor_plugin", "%s: Advertise joint_state", gazebo_ros_->info());
    }`
My URDF(Xacro): 
....
</link>
  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>
....
  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>

**Comment by snrdevs** [comment]
My URDF(Xacro): 
....
</link>
  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>
....
  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>

**Comment by snrdevs** [comment]
My URDF(Xacro): 
</link>
  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>

  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>

**Comment by nilseuropa** [comment]
Hi,

I've double checked and it works just fine. Could you please share the relevant part of your URDF?

**Comment by snrdevs** [comment]
Hi, @nilseuropa , I've build a mobile robot. It has differential drive kinematics, driven by two wheels and 4 castor wheels. When I try to implement the DC motor plugin my wheels don't turn. So I implemented the joint motor plugin. 
My goal is implement any of the motors,  then create a control algorithm for disturbance rejection simulation on motors (via disturbance observer - I'll use Simulink at this stage). Do you offer anything? Thanks in advance. Corresponding Xacro is below:

  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      
      <mass value="1.7331" />
      <inertia
        ixx="0.0096445"
        ixy="8.1545E-09"
        ixz="2.7339E-08"
        iyy="0.018393"
        iyz="-2.1331E-07"
        izz="0.0096438" />
    </inertial>     
    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://agv_description/meshes/left_wheel.STL" />
      </geometry>
      <material name="wheel_green" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://agv_description/meshes/left_wheel.STL" />
      </geometry>
    </collision>
  </link>

   
  
  

  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="left_motor" parent_link="base_link" child_link="left_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>

  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.7331" />
       <inertia
        ixx="0.0096445"
        ixy="8.1545E-09"
        ixz="2.7339E-08"
        iyy="0.018393"
        iyz="-2.1331E-07"
        izz="0.0096438" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://agv_description/meshes/right_wheel.STL" />
      </geometry>
      <material name="wheel_green" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://agv_description/meshes/right_wheel.STL" />
      </geometry>
    </collision>
  </link>

  <xacro:include filename="$(find agv_description)/xacro/joint_motor.xacro"/>
  <xacro:joint_motor motor_name="right_motor" parent_link="base_link" child_link="right_wheel">
    <xacro:property name="params_yaml" value="$(find agv_description)/params/joint_motor.yaml"/>
    <origin xyz="0 -0.2605 0" rpy="0 0 0"/>
  </xacro:joint_motor>
