### ISSUE TITLE
URDF Joints Collapse at Global Zero

### ISSUE THREAD

**Issue by snrdevs** [nilseuropa/gazebo_ros_motors#4]
Hi, I was trying some motor parameters, then I saw that if motor resistance is below 1, Gazebo spawns all links at global zero.

**Comment by nilseuropa** [comment]
Oh, that looks fun - i'll look into it this weekend.

**Comment by nilseuropa** [comment]
Hi, sorry I had no time recently, but low behold version 1.0 is now dynamically reconfigurable and it checks automagically for the valid differential solver space. So next time the solver would collapse upon itself it will self correct and send you a warning.
