### ISSUE TITLE
Encoder skipping ticks

### ISSUE THREAD

**Issue by gftabor** [nilseuropa/gazebo_ros_motors#6]
I was looking at the way you handle the velocity -> encoder ticks calculation and it seems obvious that individual ticks will be missed. How bad this will be is directly related to ticks per revolution / sample rate. If in a loop your velocity is 5.33333 ticks per update rate at a constant velocity forever you will increase by 5 ticks per loop. The off number tick will never be counted and every 3 update rates you will have not counted a tick that should have been counted.

Seems like to handle this properly you would need to keep the current rotation of the sensor as a float and only cast it to an int when broadcasting the current encoder tick.

https://github.com/nilseuropa/gazebo_ros_motors/blob/master/src/gazebo_ros_dc_motor.cpp#L312

**Comment by gftabor** [comment]
Should probably also mention 5.6666 per update rate over 3 updates should read 17 total ticks, 5,6,6 and the current system would produce 18 ticks. So it also generates ticks

Unless I am missing something?

**Comment by nilseuropa** [comment]
Hi Griffin,

thanks for pointing it out, you are correct. I've pushed a fix. If you have more suggestions please feel free to drop a pull request.
