### ISSUE TITLE
Different axes for different motors

### ISSUE THREAD

**Issue by aman765m** [nilseuropa/gazebo_ros_motors#7]
hi, I wanted to insert 4 motors (joint motor) in my model. But in the 'my_model'.xacro file, i couldn't find a way to give different axes for them as the axis is defined in the joint_motor.xacro... I tried defining a property named axis with different values each time i call for different motor but that didn't work! I am a beginner in ROS and hence this may be a silly question but i really need help...

**Comment by mtc-20** [comment]
Probably a little late, but I also ran into this same issue while helping somebody else, I made changes so that you can now
- specify axis as a parameter/argument
- have more than one instance of the plugin in the same model


I'll put up a PR for future people who come across this issue

**Comment by nilseuropa** [comment]
Dear Thomas, 

thank you for your kind contribution.

m.
